/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import classes.Company;
import java.awt.BorderLayout;
import java.awt.Color;

/**
 *
 * @author juann
 */
public class MainView extends javax.swing.JFrame {
    
    int xMouse, yMouse;
    Company dell, apple;    
    ConfigurationView configurationView;
    
    public MainView() {
        initComponents();
        this.dell = null;
        this.apple = null;
        
        this.configurationView = new ConfigurationView(this.dell, this.apple);
        this.configurationView.setSize(800, 410);
        this.configurationView.setLocation(0, 0);
        
        body.removeAll();
        body.add(configurationView, BorderLayout.CENTER);
        body.revalidate();
        body.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        body = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        configurationButton = new javax.swing.JButton();
        dellButton = new javax.swing.JButton();
        appleButton = new javax.swing.JButton();
        exit = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        body.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout bodyLayout = new javax.swing.GroupLayout(body);
        body.setLayout(bodyLayout);
        bodyLayout.setHorizontalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        bodyLayout.setVerticalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );

        jPanel1.add(body, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 800, 410));

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        configurationButton.setBackground(new java.awt.Color(204, 255, 255));
        configurationButton.setText("Configuracion");
        configurationButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                configurationButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                configurationButtonMouseExited(evt);
            }
        });
        configurationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                configurationButtonActionPerformed(evt);
            }
        });
        header.add(configurationButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 40));

        dellButton.setBackground(new java.awt.Color(204, 255, 255));
        dellButton.setText("Dell");
        dellButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dellButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dellButtonMouseExited(evt);
            }
        });
        dellButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dellButtonActionPerformed(evt);
            }
        });
        header.add(dellButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 120, 40));

        appleButton.setBackground(new java.awt.Color(204, 255, 255));
        appleButton.setText("Apple");
        appleButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                appleButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                appleButtonMouseExited(evt);
            }
        });
        appleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appleButtonActionPerformed(evt);
            }
        });
        header.add(appleButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 110, 40));

        exit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitMouseExited(evt);
            }
        });
        exit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("  X");
        exit.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, -1));

        header.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, 40, 40));

        jButton1.setText("test");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        header.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, -1, -1));

        jPanel1.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void configurationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_configurationButtonActionPerformed
        // TODO add your handling code here:
        ConfigurationView configurationView = new ConfigurationView(this.dell, this.apple);
        configurationView.setSize(800, 410);
        configurationView.setLocation(0, 0);
        
        body.removeAll();
        body.add(configurationView, BorderLayout.CENTER);
        body.revalidate();
        body.repaint();
        
    }//GEN-LAST:event_configurationButtonActionPerformed

    private void dellButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dellButtonActionPerformed
        DellView dellView = new DellView();
        dellView.setSize(800, 410);
        dellView.setLocation(0, 0);
        
        body.removeAll();
        body.add(dellView, BorderLayout.CENTER);
        body.revalidate();
        body.repaint();
    }//GEN-LAST:event_dellButtonActionPerformed

    private void appleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appleButtonActionPerformed
        AppleView appleView = new AppleView();
        appleView.setSize(800, 410);
        appleView.setLocation(0, 0);
        
        body.removeAll();
        body.add(appleView, BorderLayout.CENTER);
        body.revalidate();
        body.repaint();
    }//GEN-LAST:event_appleButtonActionPerformed

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseEntered
        Color color = new Color(255, 51, 51);
        exit.setBackground(Color.red);
    }//GEN-LAST:event_exitMouseEntered

    private void exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseExited
        Color color = new Color(242, 242, 242);
        exit.setBackground(color);
    }//GEN-LAST:event_exitMouseExited

    private void configurationButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_configurationButtonMouseEntered
        Color color = new Color(152, 234, 234);
        configurationButton.setBackground(color);
    }//GEN-LAST:event_configurationButtonMouseEntered

    private void configurationButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_configurationButtonMouseExited
        Color color = new Color(204, 255, 255);
        configurationButton.setBackground(color);
    }//GEN-LAST:event_configurationButtonMouseExited

    private void dellButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dellButtonMouseEntered
        Color color = new Color(152, 234, 234);
        dellButton.setBackground(color);
    }//GEN-LAST:event_dellButtonMouseEntered

    private void dellButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dellButtonMouseExited
        Color color = new Color(204, 255, 255);
        dellButton.setBackground(color);
    }//GEN-LAST:event_dellButtonMouseExited

    private void appleButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appleButtonMouseEntered
        Color color = new Color(152, 234, 234);
        appleButton.setBackground(color);
    }//GEN-LAST:event_appleButtonMouseEntered

    private void appleButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appleButtonMouseExited
        Color color = new Color(204, 255, 255);
        appleButton.setBackground(color);
    }//GEN-LAST:event_appleButtonMouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.out.println(this.configurationView.getApple());
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton appleButton;
    private javax.swing.JPanel body;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton configurationButton;
    private javax.swing.JButton dellButton;
    private javax.swing.JPanel exit;
    private javax.swing.JPanel header;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
