/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.BorderLayout;
import java.awt.Color;

/**
 *
 * @author juann
 */
public class MainView extends javax.swing.JFrame {
    
    int xMouse, yMouse;
    
    public MainView() {
        initComponents();
        
        ConfigurationView configurationView = new ConfigurationView();
        configurationView.setSize(800, 410);
        configurationView.setLocation(0, 0);
        
        body.removeAll();
        body.add(configurationView, BorderLayout.CENTER);
        body.revalidate();
        body.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        body = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        configuration = new javax.swing.JButton();
        dell = new javax.swing.JButton();
        apple = new javax.swing.JButton();
        exit = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        body.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout bodyLayout = new javax.swing.GroupLayout(body);
        body.setLayout(bodyLayout);
        bodyLayout.setHorizontalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        bodyLayout.setVerticalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );

        jPanel1.add(body, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 800, 410));

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        configuration.setBackground(new java.awt.Color(204, 255, 255));
        configuration.setText("Configuracion");
        configuration.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                configurationMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                configurationMouseExited(evt);
            }
        });
        configuration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                configurationActionPerformed(evt);
            }
        });
        header.add(configuration, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 40));

        dell.setBackground(new java.awt.Color(204, 255, 255));
        dell.setText("Dell");
        dell.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dellMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dellMouseExited(evt);
            }
        });
        dell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dellActionPerformed(evt);
            }
        });
        header.add(dell, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 120, 40));

        apple.setBackground(new java.awt.Color(204, 255, 255));
        apple.setText("Apple");
        apple.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                appleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                appleMouseExited(evt);
            }
        });
        apple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appleActionPerformed(evt);
            }
        });
        header.add(apple, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 110, 40));

        exit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitMouseExited(evt);
            }
        });
        exit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("  X");
        exit.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, -1));

        header.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, 40, 40));

        jPanel1.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void configurationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_configurationActionPerformed
        // TODO add your handling code here:
        ConfigurationView configurationView = new ConfigurationView();
        configurationView.setSize(800, 410);
        configurationView.setLocation(0, 0);
        
        body.removeAll();
        body.add(configurationView, BorderLayout.CENTER);
        body.revalidate();
        body.repaint();
        
    }//GEN-LAST:event_configurationActionPerformed

    private void dellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dellActionPerformed
        DellView dellView = new DellView();
        dellView.setSize(800, 410);
        dellView.setLocation(0, 0);
        
        body.removeAll();
        body.add(dellView, BorderLayout.CENTER);
        body.revalidate();
        body.repaint();
    }//GEN-LAST:event_dellActionPerformed

    private void appleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appleActionPerformed
        AppleView appleView = new AppleView();
        appleView.setSize(800, 410);
        appleView.setLocation(0, 0);
        
        body.removeAll();
        body.add(appleView, BorderLayout.CENTER);
        body.revalidate();
        body.repaint();
    }//GEN-LAST:event_appleActionPerformed

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseEntered
        Color color = new Color(255, 51, 51);
        exit.setBackground(Color.red);
    }//GEN-LAST:event_exitMouseEntered

    private void exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseExited
        Color color = new Color(242, 242, 242);
        exit.setBackground(color);
    }//GEN-LAST:event_exitMouseExited

    private void configurationMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_configurationMouseEntered
        Color color = new Color(152, 234, 234);
        configuration.setBackground(color);
    }//GEN-LAST:event_configurationMouseEntered

    private void configurationMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_configurationMouseExited
        Color color = new Color(204, 255, 255);
        configuration.setBackground(color);
    }//GEN-LAST:event_configurationMouseExited

    private void dellMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dellMouseEntered
        Color color = new Color(152, 234, 234);
        dell.setBackground(color);
    }//GEN-LAST:event_dellMouseEntered

    private void dellMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dellMouseExited
        Color color = new Color(204, 255, 255);
        dell.setBackground(color);
    }//GEN-LAST:event_dellMouseExited

    private void appleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appleMouseEntered
        Color color = new Color(152, 234, 234);
        apple.setBackground(color);
    }//GEN-LAST:event_appleMouseEntered

    private void appleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appleMouseExited
        Color color = new Color(204, 255, 255);
        apple.setBackground(color);
    }//GEN-LAST:event_appleMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton apple;
    private javax.swing.JPanel body;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton configuration;
    private javax.swing.JButton dell;
    private javax.swing.JPanel exit;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
