/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import classes.Company;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author juann
 */
public class SimulationView extends javax.swing.JPanel {

    Company apple, dell;
    String[] valuesApple;
    String[] valuesDell;
    public SimulationView(String[] valuesApple, String[] valuesDell, String dayDuration, String deadline) {
        initComponents();
        initValues(valuesApple, valuesDell, dayDuration, deadline);
        this.apple = null;
        this.dell = null;
        this.valuesApple = valuesApple;
        this.valuesDell = valuesDell;
    }
    
    
    public void startSimulation(){
        
    }
    
    public final void initValues(String[] valuesApple, String[] valuesDell, String dayDuration, String deadline){
        W_mb_Apple.setText(valuesApple[1]);
        W_cpu_Apple.setText(valuesApple[2]);
        W_ram_Apple.setText(valuesApple[3]);
        W_ps_Apple.setText(valuesApple[4]);
        W_gpu_Apple.setText(valuesApple[5]);
        C_mb_Apple.setText("0");
        C_cpu_Apple.setText("0");
        C_ram_Apple.setText("0");
        C_ps_Apple.setText("0");
        C_gpu_Apple.setText("0");

        
        W_mb_Dell.setText(valuesDell[1]);
        W_cpu_Dell.setText(valuesDell[2]);
        W_ram_Dell.setText(valuesDell[3]);
        W_ps_Dell.setText(valuesDell[4]);
        W_gpu_Dell.setText(valuesDell[5]);
        C_mb_Dell.setText("0");
        C_cpu_Dell.setText("0");
        C_ram_Dell.setText("0");
        C_ps_Dell.setText("0");
        C_gpu_Dell.setText("0");
               
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        startSimulation = new javax.swing.JButton();
        Separator1 = new javax.swing.JPanel();
        Separator = new javax.swing.JPanel();
        panelApple = new javax.swing.JPanel();
        computersApple = new javax.swing.JLabel();
        gpuComputersApple = new javax.swing.JLabel();
        gpuComputersSelledApple = new javax.swing.JLabel();
        computersSelledApple = new javax.swing.JLabel();
        deadlineApple = new javax.swing.JLabel();
        pmStatusApple = new javax.swing.JLabel();
        discountPmApple = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        W_mb_Apple = new javax.swing.JLabel();
        W_cpu_Apple = new javax.swing.JLabel();
        W_ram_Apple = new javax.swing.JLabel();
        W_ps_Apple = new javax.swing.JLabel();
        C_mb_Apple = new javax.swing.JLabel();
        C_cpu_Apple = new javax.swing.JLabel();
        C_ram_Apple = new javax.swing.JLabel();
        C_ps_Apple = new javax.swing.JLabel();
        L_mb_Apple = new javax.swing.JLabel();
        L_cpu_Apple = new javax.swing.JLabel();
        L_ram_Apple = new javax.swing.JLabel();
        L_ps_Apple = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        W_gpu_Apple = new javax.swing.JLabel();
        C_gpu_Apple = new javax.swing.JLabel();
        L_gpu_Apple = new javax.swing.JLabel();
        dayCounter = new javax.swing.JLabel();
        panelDell = new javax.swing.JPanel();
        pmStatusDell = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        computersSelledDell = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        computersDell = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        gpuComputersDell = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        gpuComputersSelledDell = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        deadlineDell = new javax.swing.JLabel();
        discountPmDell = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel44 = new javax.swing.JLabel();
        W_cpu_Dell = new javax.swing.JLabel();
        C_cpu_Dell = new javax.swing.JLabel();
        C_ps_Dell = new javax.swing.JLabel();
        W_mb_Dell = new javax.swing.JLabel();
        W_ram_Dell = new javax.swing.JLabel();
        C_ram_Dell = new javax.swing.JLabel();
        L_mb_Dell = new javax.swing.JLabel();
        L_ps_Dell = new javax.swing.JLabel();
        C_mb_Dell = new javax.swing.JLabel();
        L_ram_Dell = new javax.swing.JLabel();
        W_ps_Dell = new javax.swing.JLabel();
        L_cpu_Dell = new javax.swing.JLabel();
        W_gpu_Dell = new javax.swing.JLabel();
        C_gpu_Dell = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        L_gpu_Dell = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        startSimulation.setText("Iniciar Simulacion");
        startSimulation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startSimulationActionPerformed(evt);
            }
        });
        add(startSimulation, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 450, 150, -1));

        Separator1.setBackground(new java.awt.Color(0, 0, 0));
        add(Separator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 810, 1));

        Separator.setBackground(new java.awt.Color(0, 0, 0));
        add(Separator, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 810, 1));

        panelApple.setBackground(new java.awt.Color(153, 153, 255));
        panelApple.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, new java.awt.Color(0, 0, 0)));
        panelApple.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        computersApple.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        computersApple.setText("PC normales: ");
        panelApple.add(computersApple, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        gpuComputersApple.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        gpuComputersApple.setText("PC con GPU: ");
        panelApple.add(gpuComputersApple, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, -1, -1));

        gpuComputersSelledApple.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        gpuComputersSelledApple.setText("PC con GPU vendidas: ");
        panelApple.add(gpuComputersSelledApple, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, -1, -1));

        computersSelledApple.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        computersSelledApple.setText("PC normales vendidas: ");
        panelApple.add(computersSelledApple, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        deadlineApple.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        deadlineApple.setText("Dias que faltan para vender: ");
        panelApple.add(deadlineApple, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, -1, -1));

        pmStatusApple.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        pmStatusApple.setText("Proyect Manager estatus: ");
        panelApple.add(pmStatusApple, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        discountPmApple.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        discountPmApple.setText("Dinero descontado Proyect Manager: ");
        panelApple.add(discountPmApple, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));

        jLabel43.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel43.setText("Limite");
        panelApple.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel36.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel36.setText(" RAM");
        panelApple.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, -1, -1));

        jLabel41.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel41.setText("Componentes");
        panelApple.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, 20));

        jLabel42.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel42.setText(" CPU");
        panelApple.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 30, -1));

        jLabel39.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel39.setText("GPU");
        panelApple.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, -1, -1));

        jLabel40.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel40.setText("Trabajadores");
        panelApple.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel37.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel37.setText("Componentes");
        panelApple.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel38.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel38.setText("Motherboard");
        panelApple.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        jPanel1.setBackground(new java.awt.Color(153, 102, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Apple");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 6, -1, 20));

        panelApple.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 30));

        W_mb_Apple.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        W_mb_Apple.setText("W-mb");
        panelApple.add(W_mb_Apple, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, -1, -1));

        W_cpu_Apple.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        W_cpu_Apple.setText("W-cpu");
        panelApple.add(W_cpu_Apple, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, -1, -1));

        W_ram_Apple.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        W_ram_Apple.setText("W-ram");
        panelApple.add(W_ram_Apple, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, -1, -1));

        W_ps_Apple.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        W_ps_Apple.setText("W-ps");
        panelApple.add(W_ps_Apple, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, -1, -1));

        C_mb_Apple.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        C_mb_Apple.setText("C-mb");
        panelApple.add(C_mb_Apple, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, -1));

        C_cpu_Apple.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        C_cpu_Apple.setText("C-cpu");
        panelApple.add(C_cpu_Apple, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, -1, -1));

        C_ram_Apple.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        C_ram_Apple.setText("C-ram");
        panelApple.add(C_ram_Apple, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, -1, -1));

        C_ps_Apple.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        C_ps_Apple.setText("C-ps");
        panelApple.add(C_ps_Apple, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, -1, -1));

        L_mb_Apple.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        L_mb_Apple.setText("25");
        panelApple.add(L_mb_Apple, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, -1, -1));

        L_cpu_Apple.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        L_cpu_Apple.setText("20");
        panelApple.add(L_cpu_Apple, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, -1, -1));

        L_ram_Apple.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        L_ram_Apple.setText("55");
        panelApple.add(L_ram_Apple, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, -1, -1));

        L_ps_Apple.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        L_ps_Apple.setText("35");
        panelApple.add(L_ps_Apple, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, -1, -1));

        jLabel45.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel45.setText("PowerSupply");
        panelApple.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, -1, -1));

        W_gpu_Apple.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        W_gpu_Apple.setText("W-gpu");
        panelApple.add(W_gpu_Apple, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, -1, -1));

        C_gpu_Apple.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        C_gpu_Apple.setText("C-gpu");
        panelApple.add(C_gpu_Apple, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, -1, -1));

        L_gpu_Apple.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        L_gpu_Apple.setText("10");
        panelApple.add(L_gpu_Apple, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, -1, -1));

        dayCounter.setText("Dia: ");
        panelApple.add(dayCounter, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        add(panelApple, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 490));

        panelDell.setBackground(new java.awt.Color(255, 153, 204));
        panelDell.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pmStatusDell.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        pmStatusDell.setText("Proyect Manager estatus: ");
        panelDell.add(pmStatusDell, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel23.setText("RAM");
        panelDell.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, -1, -1));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel25.setText("Componentes");
        panelDell.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        computersSelledDell.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        computersSelledDell.setText("PC normales vendidas: ");
        panelDell.add(computersSelledDell, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel21.setText("Motherboard");
        panelDell.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel24.setText("PowerSupply");
        panelDell.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, -1, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel20.setText("Trabajadores");
        panelDell.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        computersDell.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        computersDell.setText("PC normales: ");
        panelDell.add(computersDell, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel27.setText("Componentes");
        panelDell.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, 20));

        gpuComputersDell.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        gpuComputersDell.setText("PC con GPU: ");
        panelDell.add(gpuComputersDell, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, -1, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel22.setText("CPU");
        panelDell.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, -1, -1));

        gpuComputersSelledDell.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        gpuComputersSelledDell.setText("PC con GPU vendidas: ");
        panelDell.add(gpuComputersSelledDell, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, -1, -1));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel26.setText("Limite");
        panelDell.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        deadlineDell.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        deadlineDell.setText("Dias que faltan para vender: ");
        panelDell.add(deadlineDell, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, -1, -1));

        discountPmDell.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        discountPmDell.setText("Dinero descontado Proyect Manager: ");
        panelDell.add(discountPmDell, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 102, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel44.setText("Dell");
        jPanel2.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 6, -1, 20));

        panelDell.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 30));

        W_cpu_Dell.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        W_cpu_Dell.setText("W-cpu");
        panelDell.add(W_cpu_Dell, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, -1, -1));

        C_cpu_Dell.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        C_cpu_Dell.setText("C-cpu");
        panelDell.add(C_cpu_Dell, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, -1, -1));

        C_ps_Dell.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        C_ps_Dell.setText("C-ps");
        panelDell.add(C_ps_Dell, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, -1, -1));

        W_mb_Dell.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        W_mb_Dell.setText("W-mb");
        panelDell.add(W_mb_Dell, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, -1));

        W_ram_Dell.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        W_ram_Dell.setText("W-ram");
        panelDell.add(W_ram_Dell, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, -1, -1));

        C_ram_Dell.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        C_ram_Dell.setText("C-ram");
        panelDell.add(C_ram_Dell, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, -1, -1));

        L_mb_Dell.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        L_mb_Dell.setText("25");
        panelDell.add(L_mb_Dell, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, -1));

        L_ps_Dell.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        L_ps_Dell.setText("35");
        panelDell.add(L_ps_Dell, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, -1, -1));

        C_mb_Dell.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        C_mb_Dell.setText("C-mb");
        panelDell.add(C_mb_Dell, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, -1, -1));

        L_ram_Dell.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        L_ram_Dell.setText("55");
        panelDell.add(L_ram_Dell, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, -1, -1));

        W_ps_Dell.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        W_ps_Dell.setText("W-ps");
        panelDell.add(W_ps_Dell, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, -1, -1));

        L_cpu_Dell.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        L_cpu_Dell.setText("20");
        panelDell.add(L_cpu_Dell, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, -1, -1));

        W_gpu_Dell.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        W_gpu_Dell.setText("W-gpu");
        panelDell.add(W_gpu_Dell, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, -1, -1));

        C_gpu_Dell.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        C_gpu_Dell.setText("C-gpu");
        panelDell.add(C_gpu_Dell, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, -1, -1));

        jLabel46.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel46.setText("GPU");
        panelDell.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, -1, -1));

        L_gpu_Dell.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        L_gpu_Dell.setText("10");
        panelDell.add(L_gpu_Dell, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, -1, -1));

        add(panelDell, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 410, 490));
    }// </editor-fold>//GEN-END:initComponents

    private void startSimulationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startSimulationActionPerformed
        System.out.println(valuesApple[6]);
        
        int[] arrayEmployeesApple = {
            Integer.parseInt(valuesApple[1]),
            Integer.parseInt(valuesApple[2]),
            Integer.parseInt(valuesApple[3]),
            Integer.parseInt(valuesApple[4]),
            Integer.parseInt(valuesApple[5]),
        };
        
        int[] arrayEmployeesDell = {
            Integer.parseInt(valuesApple[1]),
            Integer.parseInt(valuesApple[2]),
            Integer.parseInt(valuesApple[3]),
            Integer.parseInt(valuesApple[4]),
            Integer.parseInt(valuesApple[5]),
        };
        
        apple.createWorkers(arrayEmployeesApple);
        apple.createAssemblers(Integer.parseInt(valuesApple[6]));
        
        dell.createWorkers(arrayEmployeesDell);
        dell.createAssemblers(Integer.parseInt(valuesDell[6]));
        
        apple.start();
        dell.start();
    }//GEN-LAST:event_startSimulationActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel C_cpu_Apple;
    private javax.swing.JLabel C_cpu_Dell;
    private javax.swing.JLabel C_gpu_Apple;
    private javax.swing.JLabel C_gpu_Dell;
    private javax.swing.JLabel C_mb_Apple;
    private javax.swing.JLabel C_mb_Dell;
    private javax.swing.JLabel C_ps_Apple;
    private javax.swing.JLabel C_ps_Dell;
    private javax.swing.JLabel C_ram_Apple;
    private javax.swing.JLabel C_ram_Dell;
    private javax.swing.JLabel L_cpu_Apple;
    private javax.swing.JLabel L_cpu_Dell;
    private javax.swing.JLabel L_gpu_Apple;
    private javax.swing.JLabel L_gpu_Dell;
    private javax.swing.JLabel L_mb_Apple;
    private javax.swing.JLabel L_mb_Dell;
    private javax.swing.JLabel L_ps_Apple;
    private javax.swing.JLabel L_ps_Dell;
    private javax.swing.JLabel L_ram_Apple;
    private javax.swing.JLabel L_ram_Dell;
    private javax.swing.JPanel Separator;
    private javax.swing.JPanel Separator1;
    private javax.swing.JLabel W_cpu_Apple;
    private javax.swing.JLabel W_cpu_Dell;
    private javax.swing.JLabel W_gpu_Apple;
    private javax.swing.JLabel W_gpu_Dell;
    private javax.swing.JLabel W_mb_Apple;
    private javax.swing.JLabel W_mb_Dell;
    private javax.swing.JLabel W_ps_Apple;
    private javax.swing.JLabel W_ps_Dell;
    private javax.swing.JLabel W_ram_Apple;
    private javax.swing.JLabel W_ram_Dell;
    private javax.swing.JLabel computersApple;
    private javax.swing.JLabel computersDell;
    private javax.swing.JLabel computersSelledApple;
    private javax.swing.JLabel computersSelledDell;
    private javax.swing.JLabel dayCounter;
    private javax.swing.JLabel deadlineApple;
    private javax.swing.JLabel deadlineDell;
    private javax.swing.JLabel discountPmApple;
    private javax.swing.JLabel discountPmDell;
    private javax.swing.JLabel gpuComputersApple;
    private javax.swing.JLabel gpuComputersDell;
    private javax.swing.JLabel gpuComputersSelledApple;
    private javax.swing.JLabel gpuComputersSelledDell;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel panelApple;
    private javax.swing.JPanel panelDell;
    private javax.swing.JLabel pmStatusApple;
    private javax.swing.JLabel pmStatusDell;
    private javax.swing.JButton startSimulation;
    // End of variables declaration//GEN-END:variables

    public Company getApple() {
        return apple;
    }

    public void setApple(Company apple) {
        this.apple = apple;
    }

    public Company getDell() {
        return dell;
    }

    public void setDell(Company dell) {
        this.dell = dell;
    }

    public JLabel getC_cpu_Apple() {
        return C_cpu_Apple;
    }

    public void setC_cpu_Apple(JLabel C_cpu_Apple) {
        this.C_cpu_Apple = C_cpu_Apple;
    }

    public JLabel getC_cpu_Dell() {
        return C_cpu_Dell;
    }

    public void setC_cpu_Dell(JLabel C_cpu_Dell) {
        this.C_cpu_Dell = C_cpu_Dell;
    }

    public JLabel getC_gpu_Apple() {
        return C_gpu_Apple;
    }

    public void setC_gpu_Apple(JLabel C_gpu_Apple) {
        this.C_gpu_Apple = C_gpu_Apple;
    }

    public JLabel getC_gpu_Dell() {
        return C_gpu_Dell;
    }

    public void setC_gpu_Dell(JLabel C_gpu_Dell) {
        this.C_gpu_Dell = C_gpu_Dell;
    }

    public JLabel getC_mb_Apple() {
        return C_mb_Apple;
    }

    public void setC_mb_Apple(JLabel C_mb_Apple) {
        this.C_mb_Apple = C_mb_Apple;
    }

    public JLabel getC_mb_Dell() {
        return C_mb_Dell;
    }

    public void setC_mb_Dell(JLabel C_mb_Dell) {
        this.C_mb_Dell = C_mb_Dell;
    }

    public JLabel getC_ps_Apple() {
        return C_ps_Apple;
    }

    public void setC_ps_Apple(JLabel C_ps_Apple) {
        this.C_ps_Apple = C_ps_Apple;
    }

    public JLabel getC_ps_Dell() {
        return C_ps_Dell;
    }

    public void setC_ps_Dell(JLabel C_ps_Dell) {
        this.C_ps_Dell = C_ps_Dell;
    }

    public JLabel getC_ram_Apple() {
        return C_ram_Apple;
    }

    public void setC_ram_Apple(JLabel C_ram_Apple) {
        this.C_ram_Apple = C_ram_Apple;
    }

    public JLabel getC_ram_Dell() {
        return C_ram_Dell;
    }

    public void setC_ram_Dell(JLabel C_ram_Dell) {
        this.C_ram_Dell = C_ram_Dell;
    }

    public JLabel getL_cpu_Apple() {
        return L_cpu_Apple;
    }

    public void setL_cpu_Apple(JLabel L_cpu_Apple) {
        this.L_cpu_Apple = L_cpu_Apple;
    }

    public JLabel getL_cpu_Dell() {
        return L_cpu_Dell;
    }

    public void setL_cpu_Dell(JLabel L_cpu_Dell) {
        this.L_cpu_Dell = L_cpu_Dell;
    }

    public JLabel getL_gpu_Apple() {
        return L_gpu_Apple;
    }

    public void setL_gpu_Apple(JLabel L_gpu_Apple) {
        this.L_gpu_Apple = L_gpu_Apple;
    }

    public JLabel getL_gpu_Dell() {
        return L_gpu_Dell;
    }

    public void setL_gpu_Dell(JLabel L_gpu_Dell) {
        this.L_gpu_Dell = L_gpu_Dell;
    }

    public JLabel getL_mb_Apple() {
        return L_mb_Apple;
    }

    public void setL_mb_Apple(JLabel L_mb_Apple) {
        this.L_mb_Apple = L_mb_Apple;
    }

    public JLabel getL_mb_Dell() {
        return L_mb_Dell;
    }

    public void setL_mb_Dell(JLabel L_mb_Dell) {
        this.L_mb_Dell = L_mb_Dell;
    }

    public JLabel getL_ps_Apple() {
        return L_ps_Apple;
    }

    public void setL_ps_Apple(JLabel L_ps_Apple) {
        this.L_ps_Apple = L_ps_Apple;
    }

    public JLabel getL_ps_Dell() {
        return L_ps_Dell;
    }

    public void setL_ps_Dell(JLabel L_ps_Dell) {
        this.L_ps_Dell = L_ps_Dell;
    }

    public JLabel getL_ram_Apple() {
        return L_ram_Apple;
    }

    public void setL_ram_Apple(JLabel L_ram_Apple) {
        this.L_ram_Apple = L_ram_Apple;
    }

    public JLabel getL_ram_Dell() {
        return L_ram_Dell;
    }

    public void setL_ram_Dell(JLabel L_ram_Dell) {
        this.L_ram_Dell = L_ram_Dell;
    }

    public JPanel getSeparator() {
        return Separator;
    }

    public void setSeparator(JPanel Separator) {
        this.Separator = Separator;
    }

    public JPanel getSeparator1() {
        return Separator1;
    }

    public void setSeparator1(JPanel Separator1) {
        this.Separator1 = Separator1;
    }

    public JLabel getW_cpu_Apple() {
        return W_cpu_Apple;
    }

    public void setW_cpu_Apple(JLabel W_cpu_Apple) {
        this.W_cpu_Apple = W_cpu_Apple;
    }

    public JLabel getW_cpu_Dell() {
        return W_cpu_Dell;
    }

    public void setW_cpu_Dell(JLabel W_cpu_Dell) {
        this.W_cpu_Dell = W_cpu_Dell;
    }

    public JLabel getW_gpu_Apple() {
        return W_gpu_Apple;
    }

    public void setW_gpu_Apple(JLabel W_gpu_Apple) {
        this.W_gpu_Apple = W_gpu_Apple;
    }

    public JLabel getW_gpu_Dell() {
        return W_gpu_Dell;
    }

    public void setW_gpu_Dell(JLabel W_gpu_Dell) {
        this.W_gpu_Dell = W_gpu_Dell;
    }

    public JLabel getW_mb_Apple() {
        return W_mb_Apple;
    }

    public void setW_mb_Apple(JLabel W_mb_Apple) {
        this.W_mb_Apple = W_mb_Apple;
    }

    public JLabel getW_mb_Dell() {
        return W_mb_Dell;
    }

    public void setW_mb_Dell(JLabel W_mb_Dell) {
        this.W_mb_Dell = W_mb_Dell;
    }

    public JLabel getW_ps_Apple() {
        return W_ps_Apple;
    }

    public void setW_ps_Apple(JLabel W_ps_Apple) {
        this.W_ps_Apple = W_ps_Apple;
    }

    public JLabel getW_ps_Dell() {
        return W_ps_Dell;
    }

    public void setW_ps_Dell(JLabel W_ps_Dell) {
        this.W_ps_Dell = W_ps_Dell;
    }

    public JLabel getW_ram_Apple() {
        return W_ram_Apple;
    }

    public void setW_ram_Apple(JLabel W_ram_Apple) {
        this.W_ram_Apple = W_ram_Apple;
    }

    public JLabel getW_ram_Dell() {
        return W_ram_Dell;
    }

    public void setW_ram_Dell(JLabel W_ram_Dell) {
        this.W_ram_Dell = W_ram_Dell;
    }

    public JLabel getComputersApple() {
        return computersApple;
    }

    public void setComputersApple(JLabel computersApple) {
        this.computersApple = computersApple;
    }

    public JLabel getComputersDell() {
        return computersDell;
    }

    public void setComputersDell(JLabel computersDell) {
        this.computersDell = computersDell;
    }

    public JLabel getComputersSelledApple() {
        return computersSelledApple;
    }

    public void setComputersSelledApple(JLabel computersSelledApple) {
        this.computersSelledApple = computersSelledApple;
    }

    public JLabel getComputersSelledDell() {
        return computersSelledDell;
    }

    public void setComputersSelledDell(JLabel computersSelledDell) {
        this.computersSelledDell = computersSelledDell;
    }

    public JLabel getDayCounter() {
        return dayCounter;
    }

    public void setDayCounter(JLabel dayCounter) {
        this.dayCounter = dayCounter;
    }

    public JLabel getDeadlineApple() {
        return deadlineApple;
    }

    public void setDeadlineApple(JLabel deadlineApple) {
        this.deadlineApple = deadlineApple;
    }

    public JLabel getDeadlineDell() {
        return deadlineDell;
    }

    public void setDeadlineDell(JLabel deadlineDell) {
        this.deadlineDell = deadlineDell;
    }

    public JLabel getDiscountPmApple() {
        return discountPmApple;
    }

    public void setDiscountPmApple(JLabel discountPmApple) {
        this.discountPmApple = discountPmApple;
    }

    public JLabel getDiscountPmDell() {
        return discountPmDell;
    }

    public void setDiscountPmDell(JLabel discountPmDell) {
        this.discountPmDell = discountPmDell;
    }

    public JLabel getGpuComputersApple() {
        return gpuComputersApple;
    }

    public void setGpuComputersApple(JLabel gpuComputersApple) {
        this.gpuComputersApple = gpuComputersApple;
    }

    public JLabel getGpuComputersDell() {
        return gpuComputersDell;
    }

    public void setGpuComputersDell(JLabel gpuComputersDell) {
        this.gpuComputersDell = gpuComputersDell;
    }

    public JLabel getGpuComputersSelledApple() {
        return gpuComputersSelledApple;
    }

    public void setGpuComputersSelledApple(JLabel gpuComputersSelledApple) {
        this.gpuComputersSelledApple = gpuComputersSelledApple;
    }

    public JLabel getGpuComputersSelledDell() {
        return gpuComputersSelledDell;
    }

    public void setGpuComputersSelledDell(JLabel gpuComputersSelledDell) {
        this.gpuComputersSelledDell = gpuComputersSelledDell;
    }

    public JLabel getPmStatusApple() {
        return pmStatusApple;
    }

    public void setPmStatusApple(JLabel pmStatusApple) {
        this.pmStatusApple = pmStatusApple;
    }

    public JLabel getPmStatusDell() {
        return pmStatusDell;
    }

    public void setPmStatusDell(JLabel pmStatusDell) {
        this.pmStatusDell = pmStatusDell;
    }
    
    
    
    

}
